name: Build and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Wine environment
        run: |
          echo "WINEPREFIX=$HOME/.wine" >> $GITHUB_ENV
          echo "WINEARCH=win64" >> $GITHUB_ENV

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Publish to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets_GITHUB_TOKEN }}
